{% set name = "sshuttle" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/sshuttle-{{ version }}.tar.gz
  sha256: 7347ff01093d471c4e9a299b9c7abd4a18eac4fddfd4cf868bedc623cab71091

build:
  number: 0
  noarch: python
  entry_points:
    - sshuttle = sshuttle.cmdline:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - python >=3.8

test:
  imports:
    - sshuttle
    - sshuttle.methods
  commands:
    - pip check
    - sshuttle --help
  requires:
    - pip

about:
  home: https://github.com/sshuttle/sshuttle
  summary: Full-featured" VPN over an SSH tunnel
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
